export const techs = {
  common: [
    { name: 'Lodash', url: 'http://www.lodashjs.com' },
    { name: 'DayJS', url: 'https://dayjs.fenxianglu.cn' },
    { name: 'Axios', url: 'https://www.axios-http.cn/docs/intro' },
    { name: 'TypeScript', url: 'https://typescript.p2hp.com' },
    { name: 'Docker', url: 'https://www.docker.com' },
  ],
  frontend: [
    { name: 'Vue3', url: 'https://cn.vuejs.org/guide/introduction' },
    { name: 'VueRouter', url: 'https://router.vuejs.org/zh' },
    { name: 'Pinia', url: 'https://pinia.vuejs.org/zh' },
    { name: 'ElementPlus', url: 'https://element-plus.org/zh-CN' },
    { name: 'UnoCSS', url: 'https://unocss.nodejs.cn' },
    { name: 'Canvas', url: 'https://www.canvasapi.cn' },
    { name: 'ECharts', url: 'https://echarts.apache.org/zh/index.html' },
    { name: 'VueUse', url: 'https://vueuse.zhcndoc.com' },
    { name: 'IconFont', url: 'https://www.iconfont.cn' },
    { name: 'NProgress', url: 'https://juejin.cn/post/7631483990629613604' },
    { name: 'Markdown', url: 'https://imzbf.github.io/md-editor-v3/zh-CN' },
    { name: 'Vite', url: 'https://cn.vitejs.dev/config' },
  ],
  backend: [
    { name: 'NestJS', url: 'https://docs.nestjs.com' },
    { name: 'TypeORM', url: 'https://www.typeorm.net' },
    { name: 'MySQL', url: 'https://www.mysql.com/downloads' },
    { name: 'Redis', url: 'https://redis.io/docs/latest/commands' },
    { name: 'SvgCaptcha', url: 'https://github.com/produck/svg-captcha/blob/1.x/README_CN.md' },
    { name: 'ExcelJS', url: 'https://github.com/exceljs/exceljs/blob/HEAD/README_zh.md' },
    { name: 'Winston', url: 'https://github.com/winstonjs/winston/blob/master/README.md' },
    { name: 'nodemailer', url: 'https://nodemailer.com' },
    { name: 'systeminformation', url: 'https://systeminformation.io' },
    { name: 'argon2', url: 'https://github.com/ranisalt/node-argon2#readme' },
    { name: 'ip2region', url: 'https://github.com/sonofmagic/node-ip2region#readme' },
    { name: 'RBAC', url: 'https://juejin.cn/post/7359086041796968482' },
  ],
}
